### ISSUE TITLE
Revised constraints

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js-cola#1]
The constraints should be expanded to support all the usecases that Cola supports

**Comment by kamranjon** [comment]
Is [something like this](http://marvl.infotech.monash.edu/webcola/examples/disconnected_graphs.html) supported? Not specifically disconnected components - but just preventing overlap of any nodes. Can't seem to figure out the correct layout settings to make this work.

**Comment by maxkfranz** [comment]
Overlap avoidance is a built-in feature for the Cola lib, and it's on by default.
