### ISSUE TITLE
rerunning layout with compound nodes resets positions

### ISSUE THREAD

**Issue by EyMaddis** [cytoscape/cytoscape.js-cola#14]
Some context: I am rendering a graph which receives updates via a websocket connection. My goal is to add nodes at runtime and add them to the existing rendering of cytoscape. This should happen without a fully restarted layout which would update all positions, which would be very confusing for users.

[This example from webcola](http://marvl.infotech.monash.edu/webcola/examples/browsemovies.html) is pretty spot-on, since it adds nodes/edges at runtime (by clicking), but mostly keeps the already positioned nodes at their old position.

I am trying to add nodes to the the cytoscape instance at runtime, but `layout.run()` will only change the existing nodes.

I tried to work around that fact by doing:

``` js
var layout = cytoscapeInstance.makeLayout({name: 'cola', .... options... });

// receive updated elements from websocket
// ... later:

layout.options.eles = cytoscapeInstance.elements();
layout.run()
```

This kind of works, but it will restart the rendering from the beginning and will ignore the existing state of the layout. This it is the same as when I completely reinitialize cytoscape with the new data. Users have no way to follow the update animations, so they will not be able to keep track of what position the node has they just looked at.

The problem seems to be that webcola gets its own set of objects which are only calculated by using `.run()`. Since the transformation methods (from cytoscapes data structure to colas) are not public there is no way to work around this. Otherwise I could probably do the transformations on the new data myself and then call `layout.adaptor.resume()`.

Any ideas on how to solve this properly?

**Comment by maxkfranz** [comment]
Running a new force-directed layout is (almost always) the same as adding/removing elements iff the same options are used and randomisation is not used.

This demo creates a new layout each time parameters are changed by the sliders and it's smooth: http://js.cytoscape.org/demos/2ebdc40f1c2540de6cf0/

**Comment by EyMaddis** [comment]
But the problem is that the layout starts of by spreading out the nodes, as it should, but another 
call to `makeLayout(sameOptions)` and then `run()` it will ditch the previously calculated positions of nodes completely and restart from scratch.
I tried to set the positions of the nodes, but it does not matter since (I think) [this line](https://github.com/cytoscape/cytoscape.js-cola/blob/master/cytoscape-cola.js#L132) will override all positions each time `run` is called.
Since it is beginning again and I now have new nodes added, the layout changes completely. 
In your example it does not matter as the same nodes are layouted, which results in the same layout everytime (with slight variations due to the sliders).

**Comment by maxkfranz** [comment]
I don't think it should be different with that line, because the initial conditions are set from the existing node position.  Have you tried putting the new node well outside the bounding box of the existing graph before creating the new layout?  It could be that the new node creates too much force if it's in the middle?

**Comment by EyMaddis** [comment]
I did set starting position which are very spread out, but it looked exactly the same. It seemed to ignore the previous position. I also debugged into the run function and noticed that the starting positions were correctly set at the beginning. I cannot determine where the initial position are respected.

I also made a gif to show that it has to ignore the calculated positions:

![rerun](https://cloud.githubusercontent.com/assets/1409100/18381522/f42aa77c-767c-11e6-9b6c-63ba5937fa33.gif)

In my understanding rerunning the same layout on a already layouted graph should basically do nothing/very little. The `node.position()`s are set on the first run, so it really seems to override them immediately.

**Comment by maxkfranz** [comment]
It could be that compound nodes are the issue.  Alternatively, it could just be that Cola has some internal state I'm not aware of that makes it absolutely necessary to use its add/remove API for this usecase.

If it's the second case, we need to add some functions to this particular extension that wrap the Cola add/remove functions.  This isn't ideal -- because it's inconsistent with the other layouts -- but it's more important to just get the extension working for you in this usecase.

**Comment by EyMaddis** [comment]
@maxkfranz This also an issue when loading the graph in the first place. The initial rendering also uses the positions mentioned above, but this also starts from the center. So the problem might not really be the adding/removing but it seems preset positions are the issue.

**Comment by maxkfranz** [comment]
As far as I know, you have to provide Cola with those initial conditions to prevent zero distance cases.  That basically means that at init, you need to use `randomize: true` or otherwise specify unique positions for your nodes.

**Comment by EyMaddis** [comment]
I found out that it has to do with compound nodes. I have two renderings, which are using the same code base, but one with nested structures and one without. The graph that does not have compounds will update just fine, only slightly shifting it's layout, while the compound graph will always re-render from the start.

I set up a JSBin for the issue: http://jsbin.com/gutipokojo/edit?html,js,output

I would consider this a bug and edited the title.

**Comment by felixfbecker** [comment]
I have the exact same problem with compound nodes and adding nodes from a WebSocket while the layout is running:

![cyju283dmy](https://cloud.githubusercontent.com/assets/10532611/26021766/e0663e5c-3794-11e7-85c1-594117e369fc.gif)

While nodes are added (in a 500ms interval) the graph is just stuttering. Only the last layout after all nodes were added runs smoothly to its end.

Is there any update on this issue?

**Comment by maxkfranz** [comment]
If you're running a layout without the new elements, it can't take those into account.  That may be your issue.

**Comment by felixfbecker** [comment]
I am (if I didn't, the newly all new elements would just sit in the top left corner):
```ts

let layout: Cy.LayoutInstance;
getElements().subscribe(el => {
    console.log('add', el);
    if (layout) {
        layout.stop();
    }
    layout = graph.elements().makeLayout(layoutOptions);
    graph.add(el);
    layout.run();
});
```

**Comment by maxkfranz** [comment]
`el` isn't in the layout.

These two lines are in reversed order:

```js
layout = graph.elements().makeLayout(layoutOptions);
graph.add(el);

// should be
graph.add(el);
layout = graph.elements().makeLayout(layoutOptions);
```

**Comment by felixfbecker** [comment]
Sorry, I what I pasted was just the last thing I tried from all possible orders. Using the order from your example yields the exact same result as in the gif.

**Comment by maxkfranz** [comment]
Cola is probably not stable between runs for compounds.  It's harder to support compound graphs for incremental layouts than non-compound graphs.  Perhaps that's not in Cola's scope.  You could contact the author, Tim Dwyer, to find out more or if he's interested in supporting a feature like that: http://marvl.infotech.monash.edu/webcola/

If you want a layout that explicitly supports incremental compound layouts for all Cytoscape.js visual styles / features, you should try CoSE-Bilkent: https://github.com/cytoscape/cytoscape.js-cose-bilkent  It was made by Ugur Dogrusoz's lab based on Ugur's paper on the algorithm.  Ugur is an expert in compound layouts.  In any app where I needed incremental compound layouts, I would use CoSE-Bilkent.

**Comment by felixfbecker** [comment]
@maxkfranz I tried pretty much every layout there is for cytoscape, including cose-bilkent - they all had the same or similar stuttering. Shall I open an issue at the cose-bilkent repo?

**Comment by maxkfranz** [comment]
Yes, that makes sense.
