### ISSUE TITLE
does not handle destruction of cytoscape instance

### ISSUE THREAD

**Issue by EyMaddis** [cytoscape/cytoscape.js-cola#15]
When calling `cytoscapeInstance.destroy()` while the layouting is working, exceptions are thrown, because internally the cytoscape renderer is already set to `null`.
This is based on the asynchronous loop for the layout animation, because `.destroy()` might be called in between frames.

Can be solved by listening to the `destroy` event, which was introduced in this PR: https://github.com/cytoscape/cytoscape.js/pull/1527

**Comment by maxkfranz** [comment]
We should be able to safely add the check before support exists in a stable release.  The event won't be emitted until >=3.1, but it shouldn't cause any errors.

**Comment by maxkfranz** [comment]
I don't think this is strictly necessary with the change in https://github.com/cytoscape/cytoscape.js/issues/1499, but I've added an autostop on destroy in a commit.
