### ISSUE TITLE
Alignment constraint functionality

### ISSUE THREAD

**Issue by enjoiful** [cytoscape/cytoscape.js-cola#17]
Is it possible to utilize alignment constraints with cytoscape + cola? Example: http://marvl.infotech.monash.edu/webcola/examples/alignment.html
 
The above example is using D3 + Cola, and I'm wondering if the same constraint functionality is achievable with Cola + Cytoscape.

**Comment by maxkfranz** [comment]
From the readme

> The alignment option isn't as flexible as the raw Cola option. Here, only integers can be used to specify relative positioning, so it's a bit limited. If you'd like to see a more sophisticated implementation, please send a pull request.

That particular example you linked to is already possible. If you want something more expressive, please send a PR.
