### ISSUE TITLE
Performance on larger graphs

### ISSUE THREAD

**Issue by KonradHoeffner** [cytoscape/cytoscape.js-cola#19]
I have a graph with about 4000 nodes and 11000 edges but the layout already does not achieve a good result in several minutes on 500 nodes and 2000 edges. Is there a way to increase performance or is the complexity of the approach too high for larger graphs? My aim is to layout the large graph in several seconds.

**Comment by maxkfranz** [comment]
If you have questions about the layout algorithm, you should ask the author, Tim: http://marvl.infotech.monash.edu/~dwyer/

This package is just a wrapper for his lib to make it work easily with cyjs: http://marvl.infotech.monash.edu/webcola/
