### ISSUE TITLE
elongated layout

### ISSUE THREAD

**Issue by KonradHoeffner** [cytoscape/cytoscape.js-cola#20]
I expect the layout to have a very rough circular boundary but it is always much larger in one dimension than in the other, see screenshot:
![elongated](https://user-images.githubusercontent.com/839577/27482863-64765bec-5823-11e7-9710-ad7493dc7a2a.png)

Generated using:

```
graph.cy.layout(
      {
        name:"cola",
        maxSimulationTime: 200,
        fit: true
      }).run();
```

This happens both if the nodes have no assigned position or are placed randomly, and also if I use infinite mode and with fit:false. The data doesn't seem to contain large chains either.

For comparison, the result of the "cose" layout:
![cose](https://user-images.githubusercontent.com/839577/27483232-d4c6a5a4-5824-11e7-8d4f-8886938d6bca.png)

**Comment by maxkfranz** [comment]
If you have questions about the layout algorithm, you should ask the author, Tim: http://marvl.infotech.monash.edu/~dwyer/

This package is just a wrapper for his lib to make it work easily with cyjs: http://marvl.infotech.monash.edu/webcola/
