### ISSUE TITLE
Quickly replacing cytoscape instance instance causes error

### ISSUE THREAD

**Issue by josephrocca** [cytoscape/cytoscape.js-cola#21]
If I quickly "replace" a cytoscape instance when using the cola layout, I get this:
```
TypeError: Cannot read property '0' of undefined  at boundingBoxImpl
```
Here's a minimal replication: http://jsbin.com/yefibebebe/3/edit?html,output

If you replace this line:
```
container: cyCtn,
```
With this:
```
container: wrapper,
```
(i.e. use the same element both times) Then the problem goes away.

Thanks for your work on this extension!

**Comment by maxkfranz** [comment]
You can't keep running a layout while you destroy a graph instance.
