### ISSUE TITLE
With animation enabled, layout always takes max time

### ISSUE THREAD

**Issue by pcurrivan** [cytoscape/cytoscape.js-cola#22]
This seems to be caused by the call to adaptor.resume() in the position event handler.  

I'm not clear exactly what that position event handler is supposed to do.  I'm guessing it's supposed to give the layout more time if someone drags a node or something during the layout, but every call to resume sets cola's alpha to 0.1, which doesn't seem like a reliably good idea.  

BTW I also noticed that scrCola.px and scrCola.py are used there, but I don't see them referenced anywhere else.  Maybe those should be just scrCola.x and scrCola.y?

(using 1.6.0)

**Comment by maxkfranz** [comment]
Addressed in 2.0.1

The `resume()` calls were necessary at some point for at least one usecase, but they don't seem to be necessary now (at least with the latest version of `webcola`).  `infinite: true` mode still needs it.

> BTW I also noticed that scrCola.px and scrCola.py are used there, but I don't see them referenced anywhere else. Maybe those should be just scrCola.x and scrCola.y?

IIRC, you can't set the positions directly in Cola's object.  Those will get overridden so your set would have no effect.  You have to set `px` and `py` deltas.  They probably should have been called `dx` and `dy`, but the author of Cola probably had a reason for the naming.
