### ISSUE TITLE
Compound nodes not given in "alignment" config function

### ISSUE THREAD

**Issue by pmackay** [cytoscape/cytoscape.js-cola#23]
I'm trying to add a constraint that will order some compound nodes, but it looks like the only nodes given to the `alignment` function are child nodes. Is this expected? Is there any approach to constraining the layout of just compound nodes?

**Comment by maxkfranz** [comment]
Generally, a layout is going to consider compound nodes as just a criterion to minimise the distance between its descendants --- as to minimise the area used by the compound.  It would make more sense to set constraints on the non-parent, descendants instead.

I would expect Cola to behave this way.  If you want more details, you should ask the author of Cola.  This is just a wrapper lib for Cytoscape.
