### ISSUE TITLE
Switching layout when cola is still animating

### ISSUE THREAD

**Issue by janhartmann** [cytoscape/cytoscape.js-cola#26]
I currently have an issue where I have a control panel to switch between multiple views of a graph. One if them is the cola view.

I do however have one problem that I can not switch from cola to another view, when the cola layout is animating. The other view just simply flashes fro a millisecond and then the cola layout is back.

I have narrowed it down to my `infinity: true` setting overridding also on layout change. 

Any recommendations?

**Comment by maxkfranz** [comment]
Just `layout.stop()` before a new layout
