### ISSUE TITLE
Incorrect link to the demo in readme

### ISSUE THREAD

**Issue by kirtanp** [cytoscape/cytoscape.js-cola#27]
Link to the demo is not working in readme. Correct link is probably http://js.cytoscape.org/demos/colajs-graph/ I think?

**Comment by maxkfranz** [comment]
The demo is a work-in-progress for https://github.com/cytoscape/cytoscape.js/issues/1926.  It will be automatically published on the next release to npm and it will be automatically updated thereafter by npm scripts on publish.  The idea is to have the extension demos live in each extension's repo.

If you want to refer to the readme for the current release, you should either view it on [npm](https://www.npmjs.com/package/cytoscape-cola) or from a [git tag](https://github.com/cytoscape/cytoscape.js-cola/blob/2.0.1/README.md).
