### ISSUE TITLE
randomize parameter not working

### ISSUE THREAD

**Issue by daana81** [cytoscape/cytoscape.js-cola#28]
cola layout does not initialize the nodes and edges at different positions when initial layout has been provided with randomize parameter.All  nodes gets defined for position  0,0

**Comment by maxkfranz** [comment]
I confirmed that it's working on the demo.  `randomize: false` gives the same result every time --- because the initial conditions are the same.  `randomize: true` gives a different result each time --- because the initial conditions are different.
