### ISSUE TITLE
Behaviour does not suggest nodeDimensionsIncludeLabels is true by default

### ISSUE THREAD

**Issue by pmackay** [cytoscape/cytoscape.js-cola#30]
The README says value is `undefined` but is `(default true)`. When testing I found that by defining it explicitly to true only then did it stop labels overlapping.

**Comment by maxkfranz** [comment]
The default is `undefined` so that the layout can defer to whatever default is set for `node.layoutDimensions()` in the core.  This should be made clearer in the docs.
