### ISSUE TITLE
Accessing window.variable breaks layout in server side

### ISSUE THREAD

**Issue by metincansiper** [cytoscape/cytoscape.js-cola#32]
When I try to run this layout on server side I got an error caused by [this line](https://github.com/cytoscape/cytoscape.js-cola/blob/master/src/cola.js#L4). It works for me when I change each ```window.variable``` in that line as ```global.variable``` but I am not sure if this is the correct way to go.

**Comment by maxkfranz** [comment]
It's probably best just to paste in a raf polyfill.  There are lots of them around.  You could copy the one from the main cyjs lib.
