### ISSUE TITLE
Blurry nodes during animation

### ISSUE THREAD

**Issue by laurentpierson** [cytoscape/cytoscape.js-cola#35]
Hi,

I am noticing blurry nodes while zooming during the animation (using `animate:true`), any idea if this can be avoided?

During animation:
![during](https://user-images.githubusercontent.com/1669973/48702243-bb308e00-ebf0-11e8-997e-5dd1402bbf64.png)

After:
![after](https://user-images.githubusercontent.com/1669973/48702245-bbc92480-ebf0-11e8-9c46-9f35aafd958c.png)

**Comment by maxkfranz** [comment]
Please provide a demo that reproduces your issue.

Include version numbers of all libraries used.
