### ISSUE TITLE
Edges in compound nodes don't animate properly

### ISSUE THREAD

**Issue by nikosai** [cytoscape/cytoscape.js-cola#37]
When I set `infinite: true` and `fit: false`, edges in compound nodes don't animate properly.

## To reproduce
In `demo-compound.html`, simply change the `layout` option as below:

```js
layout: {
  name: 'cola',
  infinite: true,
  fit: false
},
```

**Comment by maxkfranz** [comment]
See https://github.com/cytoscape/cytoscape.js/issues/2440
