### ISSUE TITLE
(Question) Does the current version cola layout supports directed graph pointing downward?

### ISSUE THREAD

**Issue by nanatiris** [cytoscape/cytoscape.js-cola#4]
I am new to Cytoscape JS and have just started to create a base skeleton for my use case. I'm trying to produce a directed graph which has a hierarchical layout. I noticed that on cola's website it has a use case like this:  http://marvl.infotech.monash.edu/webcola/examples/downwardedges.html

I'm not sure if the current version of the extension already supports this. If yes, what options should I put?

Thanks for your help!

**Comment by maxkfranz** [comment]
```js
flow: undefined, // use DAG/tree flow layout if specified, e.g. { axis: 'y', minSeparation: 30 }
```

https://github.com/cytoscape/cytoscape.js-cola#api
