### ISSUE TITLE
Layout not respecting bounding box

### ISSUE THREAD

**Issue by crognale** [cytoscape/cytoscape.js-cola#43]
I have a 400x400 box, with some nodes fixed along the lefthand side (x=0) and some along the righthand side (x=400) by setting node.position in Cytoscape. However when I set the layout with cola, many of the remaining nodes end up outside the boundingBox I defined, and the viewport has to zoom out to accommodate them:
![image](https://user-images.githubusercontent.com/1697266/81073369-88965600-8eb5-11ea-96a0-8ebefba056e2.png)

Setting a boundingBox doesn't seem to have any effect on the simulation as far as I can tell.

Things I have tried:
* in layout{}, setting boundingBox{x1, y1, x2, y2}
* Setting boundingBox{x1, y1, w, h}
* Setting fit=false
* Setting unconstrIter = 0
* in Cytoscape config, setting zoomingEnabled = false
* Using node.renderedPosition instead of node.position to fix lefthand and righthand nodes

**Comment by maxkfranz** [comment]
This extension is just a wrapper for Cola.  If you don’t like how Cola behaves, you should file an issue with Cola itself.

I looks like you probably over-constrained the system, but I’m not a Cola expert.  Could that many nodes fit inside a 400x400 (model px) box without overlap?

**Comment by danddinh** [comment]
@crognale have you found out how to make boundingBox option work?
