### ISSUE TITLE
Does cola support `top-center` constraint

### ISSUE THREAD

**Issue by Does666** [cytoscape/cytoscape.js-cola#45]
I have read this wiki : https://github.com/tgdwyer/WebCola/wiki/Constraints

I would like to know if it is possible to achieve such a constraint that always fix a node to `top-center` of the topology.  In other word, after layout finished, a specific node is alway on the top and center , and the rest nodes is below.

**Comment by maxkfranz** [comment]
If you have a feature that you'd like to have from Cola in this extension, you're welcome to test it out and create a pull request for it.  A lot of useful features have been added to Cytoscape by the community over the years, so if you're interested, it would be great if you would carry on that tradition.
