### ISSUE TITLE
Why Cytoscape.js-cola layout is not spanning the entire width of a bootstrap card?

### ISSUE THREAD

**Issue by wasimaftab** [cytoscape/cytoscape.js-cola#52]
I am using cola layout to render a Cytoscape graph inside a bootstrap card element in an electron app. However, the graph mostly tries to span vertically and in spite of having plenty of spaces in the horizontal direction, it does not span there. Because of this, the node labels become completely illegible. See the following screenshot.

![Cytoscape_Not_Spanning3](https://user-images.githubusercontent.com/29901809/100882151-23d4c580-34af-11eb-9796-f6c20d3710c6.png)

**To reproduce the issue please use the following Electron fiddle gist:**
https://gist.github.com/wasimaftab/33ab4ef9134b8c2b4c7afed4392b6520

I'm using `cytoscape@3.16.1` and `cytoscape-cola@2.4.0`

**Comment by maxkfranz** [comment]
Have you posted a minimally reproducible example (i.e. without electron) the Cola project's issue tracker?

https://github.com/tgdwyer/WebCola

**Comment by wasimaftab** [comment]
> Have you posted a minimally reproducible example (i.e. without electron) the Cola project's issue tracker?
> 
> https://github.com/tgdwyer/WebCola

I just posted a minimally reproducible example (without Electron), here it is https://github.com/tgdwyer/WebCola/issues/314
