### ISSUE TITLE
Bounding box not respected

### ISSUE THREAD

**Issue by pkovanen** [cytoscape/cytoscape.js-cola#66]
I noticed there is an existing issue:

https://github.com/cytoscape/cytoscape.js-cola/issues/43

regarding bounding box, and I wanted to check if there is any new information if it should work.

I tested the layout with several different bounding box values and I didn't see them affecting the layout at all. Layout options are:

      name: "cola",
      animate: false,
      idealEdgeLength: 50,
      quality: "proof",
      randomize: true,
      nodeDimensionsIncludeLabels: false,
      nodeRepulsion: 8000,
      edgeElasticity: 0.45,
      nestingFactor: 0.1,
      numIter: 100000,
      gravity: 0.25,
      fit: true,

And I tested with several boundingBox values, including:

      boundingBox: {x1:0,y1:0,w:1000,h:1000}
      boundingBox: {x1:0,y1:0,w:1000,h:500}
      boundingBox: {x1:0,y1:0,w:500,h:1000}

All created an identical graph:

![image](https://user-images.githubusercontent.com/38105193/130368801-79dfdec2-ec4b-4c81-a0d1-c83835822418.png)

Do you have a working example?

**Comment by maxkfranz** [comment]
There is a lot of nuance in what a bounding box for a layout means and how it may affect the results.  I don't have time to write out all of those details right now, as it would be many pages long.

If you're new to layouts, you should take a look at the tutorial: https://blog.js.cytoscape.org/2020/05/11/layouts/

**Comment by danddinh** [comment]
@pkovanen have you got it working? my boundingBox option is also not working

**Comment by pkovanen** [comment]
@dandeancook sorry, No I didn't get it to work.

**Comment by traut** [comment]
same issue here, bounding box is not respected
