### ISSUE TITLE
cola is undefined when not using AMD/CommonJS

### ISSUE THREAD

**Issue by dwjohnston** [cytoscape/cytoscape.js-cola#7]
Plunker: https://plnkr.co/edit/Nxjiicz2Y87ItKdv1885?p=preview

I'm trying to import my dependencies the plain HTML/JS way: 

      <head>
        <link rel="stylesheet" href="style.css">
        <script src = "cyto.js"></script>
        <script src = "cola.js"></script>
        <script src="script.js"></script>
      </head>

This will give a 'cola not defined' error on line 540. Is this the wrong way to import the dependency?

**Comment by antjkennedy** [comment]
Hi David,

You need to make sure to include the cola algorithm library from Monash Uni.

```html
<head>
    <link rel="stylesheet" href="style.css">
    <script src = "cyto.js"></script>
    <script src="http://marvl.infotech.monash.edu/webcola/cola.v3.min.js"></script>
    <script src = "cyto-cola.js"></script>
    <script src="script.js"></script>
  </head>
```

That should fix your problem.

Ant
