### ISSUE TITLE
Remove `cola` bower dependency

### ISSUE THREAD

**Issue by danpaulsmith** [cytoscape/cytoscape.js-cola#9]
Can't deploy my app anymore because bower aborts.

```bower webcola#^3.1.2                          ENORESTARGET No tag found that was able to satisfy ^3.1.2```

**Comment by maxkfranz** [comment]
Use `cytoscape-cola: 1.3.1` then.  It looks like `webcola` doesn't deploy to bower properly, so you won't be able to install `webcola` via bower anyway.

**Comment by danpaulsmith** [comment]
Thanks Max, fixed.

**Comment by maxkfranz** [comment]
Re-opening as I'll use this ticket to remove the `webcola` ref in `bower.json`

**Comment by maxkfranz** [comment]
Released as 1.4.1 with the `webcola` dependency removed for bower.  Maybe the dependency can be added back when there is better support in Cola for bower
