### ISSUE TITLE
Options object does not work when imported in React.js

### ISSUE THREAD

**Issue by Tornike-Kiknadze** [cytoscape/cytoscape.js-cola#90]
copy pasted options object 
// default layout options
var defaults = {
  animate: true, // whether to show the layout as it's running
  refresh: 1, // number of ticks per frame; higher is faster but more jerky
  maxSimulationTime: 4000, // max length in ms to run the layout
  ungrabifyWhileSimulating: false, // so you can't drag nodes during layout
  fit: true, // on every layout reposition of nodes, fit the viewport
  padding: 30, // padding around the simulation
  boundingBox: undefined, // constrain layout bounds; { x1, y1, x2, y2 } or { x1, y1, w, h }
  nodeDimensionsIncludeLabels: false, // whether labels should be included in determining the space used by a node

  // layout event callbacks
  ready: function(){}, // on layoutready
  stop: function(){}, // on layoutstop

  // positioning options
  randomize: false, // use random node positions at beginning of layout
  avoidOverlap: true, // if true, prevents overlap of node bounding boxes
  handleDisconnected: true, // if true, avoids disconnected components from overlapping
  convergenceThreshold: 0.01, // when the alpha value (system energy) falls below this value, the layout stops
  nodeSpacing: function( node ){ return 10; }, // extra spacing around nodes
  flow: undefined, // use DAG/tree flow layout if specified, e.g. { axis: 'y', minSeparation: 30 }
  alignment: undefined, // relative alignment constraints on nodes, e.g. {vertical: [[{node: node1, offset: 0}, {node: node2, offset: 5}]], horizontal: [[{node: node3}, {node: node4}], [{node: node5}, {node: node6}]]}
  gapInequalities: undefined, // list of inequality constraints for the gap between the nodes, e.g. [{"axis":"y", "left":node1, "right":node2, "gap":25}]
  centerGraph: true, // adjusts the node positions initially to center the graph (pass false if you want to start the layout from the current position)

  // different methods of specifying edge length
  // each can be a constant numerical value or a function like `function( edge ){ return 2; }`
  edgeLength: undefined, // sets edge length directly in simulation
  edgeSymDiffLength: undefined, // symmetric diff edge length in simulation
  edgeJaccardLength: undefined, // jaccard edge length in simulation

  // iterations of cola algorithm; uses default values on undefined
  unconstrIter: undefined, // unconstrained initial layout iterations
  userConstIter: undefined, // initial layout iterations with user-specified constraints
  allConstIter: undefined, // initial layout iterations with all constraints including non-overlap
};
which then gets passed to CytoscapeComponent, does not seem to do its job, when imported (be it default or named import) from another js file

**Comment by maxkfranz** [comment]
Post your issue in the react component repo, as that's where it would need to be resolved: https://github.com/plotly/react-cytoscapejs

The Plotly folks are usually pretty responsive.

**Comment by Tornike-Kiknadze** [comment]
> Post your issue in the react component repo, as that's where it would need to be resolved: https://github.com/plotly/react-cytoscapejs
> 
> The Plotly folks are usually pretty responsive.

Thanks a lot, btw, is there a documentation specific to cola layout anywhere on the internet ?

**Comment by maxkfranz** [comment]
The readme for the Cola layout and the React component should have all the steps to import any extension.  

If you have trouble, you may need to make accommodations in your build system -- or the guys at Plotly may need to update their type definitions in the React component repo.
